### ISSUE TITLE
Automation not working

### ISSUE THREAD

**Issue by choppir** [waliori/youtube_automatic_translation#6]
Hi Waliori,

Ok so i've installed everything and run it, looks like its doing it, but nothing is working...

Here's a video to see what it does:
https://www.dropbox.com/scl/fi/qcqddpjry4xtb2olk901v/ScreenRecorderProject15.mp4?rlkey=in2251xp2x8bkato75z1h8ovd&dl=0

Thank you
Choppir

**Comment by waliori** [comment]
@choppir weird this bug, is it after the update?

**Comment by choppir** [comment]
yes i made a new one actually - didnt update my old one

**Comment by choppir** [comment]
also, do you mean YouTube update or updating my Power flow?

**Comment by waliori** [comment]
@choppir there was a mis-copy/paste on the shared subflow, thank you
